### ISSUE TITLE
Handling Defer, Panic, and Recover for Controller Events

### ISSUE THREAD

**Issue by gokulpch** [keikoproj/iam-manager#26]
**Is this a BUG REPORT or FEATURE REQUEST?**:
FEATURE REQUEST

**What happened**:
If there are issues with the master-role or a wrong spec used to create a iamrole object (like some indentation or PolicyDocument/Statements missing in the spec), Controller pod is unable to handle the exception and transitioning to "crashloopback"

**What you expected to happen**:
The process should log the event and the pod should remain to handle incoming requests.

**How to reproduce it (as minimally and precisely as possible)**:
Create a IAM role with a wrong spec. For example:
```
apiVersion: iammanager.keikoproj.io/v1alpha1
kind: Iamrole
metadata:
  name: iamrole-sample-4
spec:
    Statement:
      -
        Action:
          - "sts:Describe"
          - "kms:ListKeys"
          - "kms:PutKeyPolicy"
          - "kms:ListAliases"
```

**Anything else we need to know?**:

Adding defer function to Reconcile - Controller will mitigate this issue:

```
func (r *IamroleReconciler) Reconcile(req ctrl.Request) (ctrl.Result, error) {
	defer func() {
		if err := recover(); err != nil {
			fmt.Println(err)
		}
	}()
	ctx := context.WithValue(context.Background(), requestId, uuid.New())
	log := log.Logger(ctx, "controllers", "iamrole_controller", "Reconcile")
	log.WithValues("iamrole", req.NamespacedName)
	log.Info("Start of the request")
	//Get the IAM specific resource
	var iamRole iammanagerv1alpha1.Iamrole

	if err := r.Get(ctx, req.NamespacedName, &iamRole); err != nil {
		log.Error(err, "unable to get iam resource from api server. ignoring it as the event will be back once its available")
		return ctrl.Result{}, ignoreNotFound(err)
	}
```

**Environment**:
- iam-manager version
- Kubernetes version :
```
$ kubectl version -o yaml
```

**Other debugging information (if applicable)**:

```
- controller logs:
```
$ kubectl logs <iam-manager>
```
